import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/themeprovider.";
import { Toaster } from "@/components/ui/sonner"
import { headers } from "next/headers";
import PrivyProvider from "@/lib/config/privy-provider";
import AuthGuard from "@/components/auth-guard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fluid Agent Marketplace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get('cookie')
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrivyProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <Toaster />
            <AuthGuard>
              {children}
            </AuthGuard>
          </ThemeProvider>
        </PrivyProvider>
      </body>
    </html>
  );
}
